### ISSUE TITLE
JS Syntax task one.

### ISSUE THREAD

**Issue by aliaksej** [AliaksandrStaliarou/js#3]
- [x] Create branch `JS-3-write-function` in terminal (cmd.exe).
- [x] Create folder with name `js-syntax` and create index.html and `sum.js` file in this folder.
- [x] Write function which calculates sum of 2 numbers.
- [x] Write sum of `1` and `2`, `3` and `4` in html page with `document.write(string)` method using `sum(number1, number2)`.
[Using document.write method](http://learn.javascript.ru/document-write)

**Comment by AliaksandrStaliarou** [comment]
Branch was created in github not in cmd.exe

**Comment by aliaksej** [comment]
great job, Alex!
